language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{drop,create,migrate}
- bundle exec rspec
deploy:
  provider: heroku
  api_key: ENV['api_key']
  app: https://dashboard.heroku.com/apps/secret-waters-04726
  run: rails db:migrate
